### ISSUE TITLE
Setup CronTab for every 3 hours to run the generate_statistics.py

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc-stats-api#1]
Decide a method to run a cron job of expression `0 */3  * * *` (for every 3 hours) running the file mentioned above

If u plan to use Linux crontabs, just mention the instructions in README.md to be followed while deploying the code.

Also let's use a  variable which will keep track of timestamp of when stats was last updated and send that to frontend  along with stats

**Comment by j-tesla** [comment]
@rakaar if this is about setting up GitHub action, I would like to work.

**Comment by rakaar** [comment]
@j-tesla 
Can you please elaborate on how can we use GitHub actions here?

So this is what we thought,
the API will be deployed mostly on IaaS platform(a Digital Ocean server mostly)
A Cronjob will be set up using Linux crontabs, that run a python file(hence updating stats.json) for every 3 hours

**Comment by j-tesla** [comment]
> 
> 
> @j-tesla
> Can you please elaborate on how can we use GitHub actions here?
> 
> So this is what we thought,
> the API will be deployed mostly on IaaS platform(a Digital Ocean server mostly)
> A Cronjob will be set up using Linux crontabs, that run a python file(hence updating stats.json) for every 3 hours

I thought we can run generate_statistics.py every 3 hours using Github Actions' scheduling events ([reference](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events)) hence updating stats.json.

**Comment by rakaar** [comment]
Cool
Sounds great!

Correct me, if I am wrong
You will write a GitHub action, that for every 3 hours sends a POST request to the API
and on receiving the request the `generate_statistics.py`  will be run, hence updating the JSON file.
(i feel I have mixed Webhooks here)

Curious to see how it goes!
Assigned it to you.

**Comment by j-tesla** [comment]
Hey @rakaar! just checkin if #14 is fine. :smile:

**Comment by yashrsharma44** [comment]
@rakaar I guess we are on the way to setup the crontab?

**Comment by rakaar** [comment]
@yashrsharma44 
#18  does that using Github actions,
no need of a crontab now!
when a new commit is made here by Github Action, it can be automatically be deployed using heroku.
(no manual intervention here)
