### ISSUE TITLE
A script to generate a CSV of people with no commits

### ISSUE THREAD

**Issue by rakaar** [kossiitkgp/kwoc-stats-api#4]
In a new file,
write a python script, which uses this [JSON file](https://github.com/kossiitkgp/kwoc-stats-api/blob/master/stats.json) and generate a new CSV file with columns -`Name`, `Email` of the students with 0 commits.

For the Emails
One needs need to iterate through rows of the [CSV file](https://github.com/kossiitkgp/kwoc-stats-api/blob/master/students_.csv)
and find the email of the student,
It is recommended that u search for email in the CSV using handle, which is guarenteed to be unique rather than name which can sometimes be similar

**Comment by neodark** [comment]
No email is provided in the JSON file.

**Comment by neodark** [comment]
Here is the PR I could change the "Affiliation" with something else if you wish to.

**Comment by rakaar** [comment]
@neodark 
thanks a lot for the PR
great job 🎉

really sorry for the ambiguity,
the emails are in this [CSV file](https://github.com/kossiitkgp/kwoc-stats-api/blob/master/students_.csv).

 You need to iterate through rows of the CSV file 
and find the email of the student,
It is recommended that u search for email in the CSV using `handle`, which is guarenteed to be unique rather than name which can sometimes be similar. 

Sorry for not mentioning it before hand
The Emails are needed because we have a script which can iterate thru the CSV file(which ur script will generate) of `Name, Email` and mail the people

**Comment by neodark** [comment]
Thanks for your answer! Ok no issue I will update the PR accordingly and will let you know when done.

**Comment by neodark** [comment]
As you wanted, the matching is done on the `handle` field to guarantee it is unique.

Note: The `students_.csv` file has an issue with the first capitalized letter of the `handle`. However it's not a problem, basically I did a lower case of this field when reading it to make sure we don't encounter any issue.
